### ISSUE TITLE
s option not existing for which command

### ISSUE THREAD

**Issue by ValentinLorand** [weibeld/kubectl-ctx#1]
Hello, I met a problem when installing this executable.
**Configuration :**

```bash
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```
**Problem :**
When I execute the script, I get this error (fzf is installed) : 
```bash
$ kubectl ctx
Illegal option -s
Usage: /usr/bin/which [-a] args
You must install fzf to use this plugin:

    https://github.com/junegunn/fzf

INSTALLATION

Homebrew (macOS) and Linuxbrew (Linux):
    brew install fzf

From source (macOS, Linux):
    git clone https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install

Other installation options:
    https://github.com/junegunn/fzf#installation
```

This came from _line 49_ of `kubectl-ctx` : 
```bash
which -s fzf || { fzf_missing; exit 1; }
```
No **s** option existing for the which command !

**Proposed solution :** 

Replace the line by this one :
```bash
which fzf >/dev/null || { fzf_missing; exit 1; }
```
I made this fix on my computer, and it fix the problem

Best regards,
Valentin

**Comment by weibeld** [comment]
Hi, thanks for pointing this out. I just fixed the command, so let me know if now it's okay.

**Comment by ValentinLorand** [comment]
Yes perfect, thank you :)
